### ISSUE TITLE
Aclarar qué ficheros son qué cosa

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_honey#1]
Aparte de los ficheros de ejemplo (que habría que borrar) hay un artículo.tex y un articuloHoneypot

> Y no me voy a poner a discutir sobre la elección del nombre del fichero... va de suyo que sea un artículo, normalmente se usa una palabra identificativa-congreso/revista-año.tex

Aclara también en el README.md de qué va y qué hay que descargarse para que funcione, incluyendo estilos particulares o algo.

**Comment by jlmacal** [comment]
Gracias!

Oído cocina.

Nos vemos!
