### ISSUE TITLE
Establish article objectives

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_honey#5]
What do you want to do? A survey? A study? Original results? The title is not very self-explanatory, not to mention it circumscribes to IT-scientist network infrastructure. Is it only for IT scientists? is it for any kind of scientist? Is it for any kind of university worker? Please discuss and, when decided, settle on a new title.

**Comment by jlmacal** [comment]
New title by Gustavo "Cybersecurity and honeypots: experience in a scientific network infrastructure"
